<?php

namespace Basso\VisualCalBundle\Repository;

/**
 * CalibracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalibracionRepository extends \Doctrine\ORM\EntityRepository
{
}
