<?php

namespace Basso\VisualCalBundle\Repository;

/**
 * CalibracionTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalibracionTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
