<?php

namespace Basso\VisualCalBundle\Repository;

/**
 * FabricanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FabricanteRepository extends \Doctrine\ORM\EntityRepository
{
}
