<?php

namespace Basso\VisualCalBundle\Repository;

/**
 * GageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GageRepository extends \Doctrine\ORM\EntityRepository
{
}
