<?php

namespace Basso\VisualCalBundle\Repository;

/**
 * GageUOMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GageUOMRepository extends \Doctrine\ORM\EntityRepository
{
}
