<?php

namespace Basso\VisualCalBundle\Repository;

/**
 * RyRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RyRRepository extends \Doctrine\ORM\EntityRepository
{
}
