<?php

namespace Basso\VisualCalBundle\Repository;

/**
 * RyRTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RyRTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
