<?php

namespace Basso\VisualCalBundle\Repository;

/**
 * UnidMedidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidMedidaRepository extends \Doctrine\ORM\EntityRepository
{
}
